name: cicd

env:
    repository: "${{ github.repository }}"
    run_id: "${{ github.run_number }}"
    job: "${{ github.job }}"
    commits: '[{"commitId": "${{ github.sha }}" }]'
    workspace: "${{ github.workspace }}"
    
on:
  push:
    branches: ['feature/workflows']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          repository: velivalab/sonar-github-action
          ref: v1.0.0
          token: ${{ secrets.GHP_TOKEN }}
          path: ./.github/actions/sonar-github-action

      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
          
      - name: Maven Build
        run: pwd
      
      - name: Run JUnit Tests
        run: mvn test -Dmaven.test.failure.ignore=true surefire-report:report
        
      - name: Sonar Cloud Analysis
        run: |
            echo ${{ env.workspace }}/target/surefire-reports
                   
  integrationTest:
    needs: build
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - run: echo Run integration tests.
      
  deploy:
    needs: integrationTest
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo Run deployment.
